### ISSUE TITLE
Plots in ipython notebook

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#10]
See first steps in https://github.com/BBN-Q/Auspex/commit/aa83c4a4d766262bf2a5cc4e52841751f49a7a4c

**Comment by grahamrow** [comment]
Try `test/NotebookPlottingTest.ipynb` at the new head (ea36e1d) of this branch? Made some changes — works in bokeh 0.12.4.

**Comment by dieris** [comment]
In my case, it loads bokeh, but doesn't plot anywhere...
