### ISSUE TITLE
Save settings as YAML

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/Auspex#114]
Settings in `WriteToHDF5` are saved as JSON as opposed to YAML.

**Comment by matthewware** [comment]
@grahamrow @gribeill from what I can tell WritetoHDF5 just copies json files to a new folder?  Was there ever functionality to write the setting to h5 files?

**Comment by dieris** [comment]
No, it's always been in json. I think we still want to save as yml (now), so that we can easily recover/reload past settings.

**Comment by matthewware** [comment]
Okay, I was thinking moving forward we could just do both.  Based on discussions with @grahamrow I'm just going to implement saving to the h5 and to a file.

**Comment by dieris** [comment]
That's even better

**Comment by grahamrow** [comment]
@matthewware take a look in `src/auspex/config.py` for YAML dumping inspiration. First thing to try might be writing a dumper (a la `yaml_dump`) that doesn't bother calling `add_representer` for `Include` objects? Depends on how flexible the dumper is. Next I'd try modifying what the `Dumper` returns.

**Comment by dieris** [comment]
The h5 saving is working. But the yml copies are now limited to the main config file (`measure.yml`). Should we search the file for an `!include` string and load those files? Or can we reuse the `yaml_dump` code to find those files?

**Comment by dieris** [comment]
Closed by #134 . It can be improved by saving the settings as the original yml files for better lookup.
