### ISSUE TITLE
YAML-compatible calibrations

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/Auspex#116]
Need to switch over all the calibrations to YAML:

- [ ] Cavity Search
- [ ] Qubit Search
- [x] Rabi Amplitude
- [x] Ramsey
- [x] Phase Estimation
- [ ] DRAG 
- [x] DRAG2
- [x] CR
- [x] CLEAR

Also
- [ ] Gracefully handle failed fits 

Slowly migrating things over on [`fix/yaml-calibrations`](https://github.com/BBN-Q/Auspex/tree/fix/yaml-calibrations)

**Comment by gribeill** [comment]
@dieris, Rabi, Ramsey and Phase Estimation seem to be working for me... can you give them a shot?

**Comment by dieris** [comment]
Agree, and merged after a few changes. Keeping this issue open while working through the remaining calibrations.

**Comment by gribeill** [comment]
Getting an error now when trying to run calibrations. Will investigate...

**Comment by grahamrow** [comment]
What we have has been working, but I'm going to close this since we're moving on from YAML in the near future
