### ISSUE TITLE
Static parameter method?

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#118]
Not sure if I misunderstand this, but it looks like the Parameter method defined here
 https://github.com/BBN-Q/Auspex/blob/a0e3e60aa3c63eec0a9cfae944e04c89f8dbe61c/src/auspex/exp_factory.py#L475-L477
 is modified for all future `QubitExpFactory` objects. This causes the unfortunate behavior:

```
exp = QubitExpFactory.create(...)
exp.add_qubit_sweep("q1 measure frequency", ...)
exp.add_qubit_sweep("q1 measure amplitude", ...)
```
works fine. But, the following

```
exp2 = QubitExpFactory.create(...)
exp2.add_qubit_sweep("q1 measure frequency", ...)
```
still tries to push the custom method for pulse amplitude during the sweep.

**Comment by grahamrow** [comment]
This is the third time I've been bitten by `MetaExperiment` in the same way. Parameters were getting shoved into a class variable that is shared across all instances. No longer, `__init__` to the rescue.
