### ISSUE TITLE
APS and digitizer fall out of sync in 2D sweeps

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#120]
Occasionally (again, I hope to circumstantiate this more...), the segment number slips during a repeated sweep (2D). As a result, some of the rows in the 2D data are horizontally shifted. It looks like some triggers are missed at the beginning of these rows, before the digitizer (X6) starts acquiring.

**Comment by grahamrow** [comment]
Can you try a delay in exp factory run method a la
```python
        for dig in self.digitizers:
            dig.acquire()
        await asyncio.sleep(0.5)
        if not self.cw_mode:
            for awg in self.awgs:
                awg.run()
```
and see if that makes any difference?

**Comment by dieris** [comment]
It definitely helps, although it's unclear what the minimum delay is. Closed by https://github.com/BBN-Q/Auspex/commit/bbae63bff087bffcb9e2d76ef9898b6d65983bcb until further notice.

**Comment by dieris** [comment]
Not enough... Trying with a longer delay, but need some deterministic way to figure out how long to pause

**Comment by grahamrow** [comment]
Should we explicitly ask the digitizers if they have managed to get themselves ready yet?

**Comment by dieris** [comment]
That may be the only reliable way, if not too slow.

**Comment by dieris** [comment]
I must also say that with a delay of 0.75 s, I haven't seen any problems yet.

**Comment by grahamrow** [comment]
That's pretty painful, we should look into the root cause.

**Comment by grahamrow** [comment]
Has this popped up again? @sfallek1 @dieris @matthewware @gribeill

**Comment by dieris** [comment]
I haven't seen this happening in a while
