### ISSUE TITLE
Add XY Plotter functionality

### ISSUE THREAD

**Issue by appwagner** [BBN-Q/Auspex#13]
Improve plotting so that data and parameters can be plotted against each other in a general way. For instance plot data that share an axis in common against each other,  a vs. time and b v.s time to easily produce a plot of a vs. b, in other words an X,Y plotter. This fix should also include the ability to slice the X,Y plots by some other axis or data.

**Comment by grahamrow** [comment]
Fixed in be5f043 and merged. Still rough around the edges, but close.
