### ISSUE TITLE
pypi and anaconda.org (METAISSUE)

### ISSUE THREAD

**Issue by grahamrow** [BBN-Q/Auspex#136]
The difficulty of installing certain deps (e.g. QGL, adapt) has made me wonder the following
1. Should we get more things on our bbn-q conda channel? (e.g. Auspex, adapt, Quince).
2. Should we put these things on pypi as well?
3. Should we automate either of these processes? Having a separate out-of-stream recipe relies on us taking the time to follow through.

**Comment by matthewware** [comment]
I've been wanting to at least update what we have up there.  @grahamrow can I bug you about this when we're both back in the office?

**Comment by matthewware** [comment]
@tim-rogers is working on this.
