### ISSUE TITLE
Estimate sweep time

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#141]
Predict how long a (non-adaptive) sweep will take, based on the data points already taken.

**Comment by grahamrow** [comment]
There's already a progress bar in the code, we just haven't been using. Not sure if it needs updating, but I will look into it.

**Comment by dieris** [comment]
Ooops, I forgot about it :)

**Comment by dieris** [comment]
That's right, already existing and working. Just need to initialize it before running sweeps:
`exp.init_progressbar(dims)`
