### ISSUE TITLE
Debug overhead in X6 acquisition

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#153]
Sweeps like cavity frequency etc. currently have an overhead of ~ x10 with an X6. Probably due to all streams being enabled.

**Comment by dieris** [comment]
Other channels (not in meta-info) are not explicitly [enabled](https://github.com/BBN-Q/Auspex/blob/e5b1ab7226a8ae11a1cfa5a442e6dfb480ecf72e/src/auspex/instruments/X6.py#L147-L148). Even when disabling every other channel explicitly, the overhead remains. Need to profile.

**Comment by dieris** [comment]
It turns out that most of the overhead is due to `select` in `pyqt5.lib.selectors`. This function is called ~5k times in a 10-points sweep, for a total of ~7 s.

**Comment by grahamrow** [comment]
I'm starting to look into this but am confused as to how pyqt5 is entering into this situation.

**Comment by grahamrow** [comment]
@dieris any more recent news here? Could you try the multiprocessing branches to see if things change?

**Comment by matthewware** [comment]
I think these issues are fixed now with MP and the new X6 builds?  No?

**Comment by dieris** [comment]
yeah, I think we can call this issue obsolete
