### ISSUE TITLE
Partial average for buffers

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#162]
Not sure if this is useful, but currently not supported. On partial average, the buffer is filled before the average is complete.

**Comment by dieris** [comment]
Currently only (ideally) used for [testing](https://github.com/BBN-Q/Auspex/blob/e3a71d56807f4fb22af518a6fb823c81034b6e9e/test/notatest_qubitexpfactory.py#L67), I think

**Comment by grahamrow** [comment]
Deeming this unnecessary.
