### ISSUE TITLE
Calibrations unit tests.

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/Auspex#165]
These break way too often... we should write some tests.

**Comment by matthewware** [comment]
Don't have to ask me twice.

**Comment by dieris** [comment]
See also issue in https://github.com/BBN-Q/Auspex/pull/163

**Comment by dieris** [comment]
- [x] Rabi
- [x] Ramsey
- [x] PiAmp
- [ ] DRAG
- [ ] CLEAR
- [ ] SingleShot

**Comment by matthewware** [comment]
There are now some calibration unit tests.

**Comment by grahamrow** [comment]
They exist and are working in develop again
