### ISSUE TITLE
Calibration logging with pandas?

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/Auspex#166]
Do we really need to import all of `pandas` to write the calibration log file? It seems to give intermittent errors...

**Comment by dieris** [comment]
Probably not. You can try importing just the couple of functions we are using. Still giving errors?

**Comment by dieris** [comment]
Let me know if you still have issues after this fix: https://github.com/BBN-Q/Auspex/commit/c23486696b65a8074ef9f257ac6c24c8eccfd423

**Comment by matthewware** [comment]
I guess we're going to keep pandas.  We aren't getting any intermittent errors after Diego's commit.  I'll try to find the few functions we need and only import them

**Comment by grahamrow** [comment]
No pandas. Calibration_db on its way
