### ISSUE TITLE
Holzworth not properly disconnected

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#167]
This may be an issue bigger than Auspex, as it (even more often) happens in Qlab too. Something hangs on the instrument, and can't be connected to until power cycle/reboot. @gribeill Have you experienced this?

**Comment by matthewware** [comment]
I've noticed something going wrong when an experiment crashes and and subsequent attempts o connect fail in the Holzworth driver.  I usually do a combination of restarting the kernel and/or power cycling the instrument.

**Comment by matthewware** [comment]
I believe this has been fixed with the updated Holzworth syntax
