### ISSUE TITLE
Investigate socket.inet_aton weirdness

### ISSUE THREAD

**Issue by grahamrow** [BBN-Q/Auspex#18]
On some systems (volans) this function seems to consider integers to be valid IP addresses. Courtesy of @appwagner

**Comment by appwagner** [comment]
Warning messages still needs fixing, instruments connect correctly but auspex still complains

auspex-WARNING: 2017-01-30 11:46:05,139 ----> User-provided IP 2 is a valid IP address but does not appear to be in human-readable format.
GPIBInstrument at GPIB0::2::INSTR
auspex-WARNING: 2017-01-30 11:46:05,249 ----> User-provided IP 10 is a valid IP address but does not appear to be in human-readable format.
GPIBInstrument at GPIB0::10::INSTR

**Comment by appwagner** [comment]
Oops closed issue accidentally.
