### ISSUE TITLE
Fix extra plotters for pulse calibrations in multiprocessing branch

### ISSUE THREAD

**Issue by grahamrow** [BBN-Q/Auspex#217]
I'm a little confused by this code. The logic was somewhat broken by the concurrency of some of the filters, and despite pulling from a few ends I still have a giant knot...

**Comment by dieris** [comment]
The idea here https://github.com/BBN-Q/Auspex/pull/152 was that pulse calibrations use a separate server (in addition to the default for the experiment), so that it could stay open and accumulate data  between different runs. I'll take a look, once I understand how multi processing works :)
