### ISSUE TITLE
Why just two pulse cal quadratures?

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/Auspex#229]
Anyone know why we limit people to use just the real and imag quads for pulse cal?

https://github.com/BBN-Q/Auspex/blob/c1545d045cc3d54831f99539125d26141ca743a5/src/auspex/pulse_calibration.py#L146

**Comment by dieris** [comment]
I think that the reason is that it's not obvious to get the variance of amplitude or phase

**Comment by matthewware** [comment]
I've taken a stab at this in #230.

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/Auspex/pull/230
