### ISSUE TITLE
bug in 'set_all' method in APS class in bbn.py

### ISSUE THREAD

**Issue by jaseung** [BBN-Q/Auspex#256]
I am not sure if this is the right way to report a bug. Let me know if there is a better way.

It seems that there is a bug in set_all method for APS class in bbn.py. `set_enabled`, `set_offset' and 'set_amplitude' are not applied in 'set_all' method. I temporarily fixed it and APS1 worked fine. Without this fixed, ASP1 output is disabled and offset/amplitude are not set at the beginning of experiment. 

![bbn_aps_set_all_fix](https://user-images.githubusercontent.com/22563147/40671999-843eec2c-633b-11e8-83ba-d0cf6a0d3726.PNG)

**Comment by dieris** [comment]
@jaseung thanks for finding out. That looks like a typo (also for the APS2, where we don't notice because there are only 2 channels). If you have already fixed it, please open a pull request

**Comment by dieris** [comment]
Fixed by https://github.com/BBN-Q/Auspex/pull/290
