### ISSUE TITLE
Log single-shot calibration

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#259]
Log fidelity and thresholds, analogously to https://github.com/BBN-Q/Auspex/pull/155

**Comment by dieris** [comment]
More in general, log:
- [ ] Single shot fidelities
- [ ] Coherence times
- [ ] Gate fidelities

**Comment by grahamrow** [comment]
Think this is addressed by recent calibration db additions. We just need the code to inject the values!

**Comment by dieris** [comment]
Most calibration results are now logged. See e.g.  https://github.com/BBN-Q/Auspex/pull/334,  https://github.com/BBN-Q/Auspex/pull/426, https://github.com/BBN-Q/Auspex/pull/438
