### ISSUE TITLE
use Intel IPP for channelizer

### ISSUE THREAD

**Issue by caryan** [BBN-Q/Auspex#3]
We used the Intel IPP in the the Qlab mex file version and preliminary testing shows it is ~20X faster than scipy's Cython version.  Seems enough of a speedup to make the effort to wrap.

**Comment by grahamrow** [comment]
That's no joke. Maybe we should CFFI our way through this one?

**Comment by caryan** [comment]
I don't want all of IPP as a dependency.  My plan is to statically link in the few IPP functions we need to a shared library that we compile once for all platforms and add to the repo. This worked on Windows for the mex version.

**Comment by blakejohnson** [comment]
Done, no?
