### ISSUE TITLE
APS2 log polluting Alazar log

### ISSUE THREAD

**Issue by sfallek1** [BBN-Q/Auspex#305]
See items like
```
11:48:42.243 INFO: 192.168.2.2 opening sequence file: /home/qlab/Edison/AWG/Rabi/Rabi-BBNAPS2.h5
```
popping up in the alazar.log, despite being APS2 log information.

**Comment by grahamrow** [comment]
While not an auspex issue, I'll leave this here since it's incredibly annoying...

**Comment by grahamrow** [comment]
Switched to plog for basically all of our C libraries now
