### ISSUE TITLE
Crash after few hours taking data

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#335]
To be investigated. Sorry for the dumb dump: 
<img width="1114" alt="Capture" src="https://user-images.githubusercontent.com/10402430/54871813-c824e000-4d90-11e9-86cf-932122fa6c4f.PNG">

**Comment by grahamrow** [comment]
Hmm, you get it with ZMQ, I get it with multiprocessing. I'm testing out explicit garbage collection, and think we need to be extra careful to close things...

**Comment by grahamrow** [comment]
There are now a bunch of changes on develop. Please advise on status when possible.

**Comment by matthewware** [comment]
Highly likely this was due to the file descriptors issue Graham has been fixing.  @dieris is there something you could run over the weekend for a stress test?

**Comment by dieris** [comment]
will try as soon as I switch back, on a different OS right now...
