### ISSUE TITLE
Save the current database at every exp

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#341]
Keep track of all experimental settings for every run. 
Save the current database either as a metadata field, or as a separate file if that would make the data file too large.

**Comment by grahamrow** [comment]
What is the most important use case here? That may change the best implementation.
- Have all of the input parameters necessary for analysis, post-processing (serialize)
- Rerun experiments with same parameters (serialize/deserialize)

**Comment by grahamrow** [comment]
Also, save ALL the information in the DB or just that associated with the particular experiment?

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/Auspex/pull/393
