### ISSUE TITLE
Variable SSB_FREQ for mixer cal

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#366]
The [SSB_FREQ](https://github.com/BBN-Q/Auspex/blob/5a63dc45daadbc20708a9be0db2c9f3be08edae6/src/auspex/qubit/mixer_calibration.py#L188) should be read from the channel frequency

**Comment by dieris** [comment]
As in https://github.com/BBN-Q/Auspex/commit/38ce99d7bc895f5a1fede35f0b5a8ca2da84a03b

**Comment by gribeill** [comment]
Fixed.
