### ISSUE TITLE
QGL not registered as dependency

### ISSUE THREAD

**Issue by BillyKalfus** [BBN-Q/Auspex#368]
Auspex does not install QGL during the installation process which it requires when calling:
 `from auspex.instruments import KCU105`

**Comment by gribeill** [comment]
That branch is experimental for the old APS3 development board; we don't want to have QGL as a global dependency. Try using the new feature/aps3-amc599 branch. You will have to use `from auspex.instruments.aps3 import APS3` since I haven't added the new driver to the global import scope.
