### ISSUE TITLE
"Raw" stream type doesnt create correct default pipeline

### ISSUE THREAD

**Issue by appwagner** [BBN-Q/Auspex#371]
After setting stream_type = "raw", demod, integrate and average have to added explicitly to the pipeline. This should happen automagically. 

pl["q1"].add(Demodulate(label="Demod")).add(Integrate(label="int")).add(Average(label="avg")).add(Write(label="wr"))

**Comment by gribeill** [comment]
Seems to be working for me using the current develop? Are you running `pl["q1"].create_default_pipeline(buffers=False)`?

**Comment by dieris** [comment]
I think the default behavior is correct. It's creating the pipeline raw - average - write, as expected. You do need to add Demod and Integrate manually if you wish
