### ISSUE TITLE
E8363C NWA driver broken 

### ISSUE THREAD

**Issue by appwagner** [BBN-Q/Auspex#443]
NWA drivers are broken at head of develop. Since this issue was fixed in the recent past I'm not sure how things became reverted. Needs investigation.

**Comment by grahamrow** [comment]
@gribeill The binary data poltergeist has returned!

**Comment by ranzani** [comment]
@appwagner  Andrew, can you check if you have pyvisa >=1.9.1 and pyvisa-py >=0.4.1 installed?

**Comment by appwagner** [comment]
I haven’t touched this in over a year. I’ve long forgotten what was going on

**Comment by gribeill** [comment]
Fixed by #488
