### ISSUE TITLE
Holding on writer file in cals

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#48]
Still happening occasionally. Even after closing and killing the file at the end of an experiment!

**Comment by blakejohnson** [comment]
Seems to be caused by h5py/h5py#775. Will be fixed with h5py 2.7.0 is released.

**Comment by dieris** [comment]
Replacing data writers with data buffers as @grahamrow suggested may be enough for now. I'd prefer not to save calibration data anyway

**Comment by grahamrow** [comment]
We went with DataBuffers for the time being. Merged into master.
