### ISSUE TITLE
sweep sets initial conditions redundantly

### ISSUE THREAD

**Issue by appwagner** [BBN-Q/Auspex#49]
async def sweep(self):
        # Set any static parameters
        for p in self._parameters.values():
            p.push()

sweep method sets initial conditions and then sets them again before beginning measurements. Discussion indicates that for those special cases where this is useful custom code could be written to do this, for instance in the init_instruments method of an experiment.

**Comment by grahamrow** [comment]
So, this wasn't redundant for any parameter that wasn't swept. Just caused me all sorts of problems figuring out why, e.g., the sourcemeter wasn't sourcing any voltage. Will rework to only update parameters that aren't swept.
