### ISSUE TITLE
Clear plots instead of the full ipython output

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#59]
The notebook output is cleared between calibration [runs](https://github.com/BBN-Q/Auspex/blob/6bedcb31ad4878289d5dae93e4b5d7d2ec5a039b/src/auspex/experiment.py#L435). This is good to clean up plots, but it also erases the history of the calibration.

**Comment by grahamrow** [comment]
Keeping relevant information? So demanding! I'll have to do a bit more research on this one...

**Comment by grahamrow** [comment]
This is actually harder than I thought — getting the current cell output isn't easy.

**Comment by grahamrow** [comment]
Plots will now be in a separate matplotlib client. What is the desired behavior if all that remains is text? Just leave it all?

**Comment by dieris** [comment]
I think leaving all the text sounds good...we'll try it

**Comment by grahamrow** [comment]
No longer and issue with separate matplotlib client.
