### ISSUE TITLE
Network analyzer reaveraging broken

### ISSUE THREAD

**Issue by gribeill** [BBN-Q/Auspex#71]
Driver does not block when reaverage command issued.

**Comment by caryan** [comment]
Do you know why it seems to claim it does [here](https://github.com/BBN-Q/Auspex/blob/master/src/auspex/instruments/agilent.py#L290)

**Comment by gribeill** [comment]
Yeah, it's pretty weird -- it seems to never hit the loop. I think that there is a slight delay between issuing the averaging restart command and the NA indicating that averaging is not complete. The right way to do this is using the `OPC` GPIB code, so I am implementing that now.

**Comment by caryan** [comment]
I guess an alternative is to use `*WAI` like we in the [Matlab version](https://github.com/BBN-Q/Qlab/blob/develop/common/%2BdeviceDrivers/AgilentE8363C.m#L81)

**Comment by gribeill** [comment]
Yes, after doing a bit of reading seems that is the friendlier way of interacting through SCPI. Ideally we'd use the [`*SRQ?` event registers](http://www.keysight.com/main/editorial.jspx?cc=US&lc=eng&ckey=602664-1-eng&id=602664-1-eng), but that's going to require asynchronous instruments with event handlers, which is not really a can of worms I want to open right now...
