### ISSUE TITLE
Axis names must be unique

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#73]
Currently, the axis descriptor name for e.g. a T1 sequence in QGL is `time`, the same as a `StreamSelector`. This causes [this](https://github.com/BBN-Q/Auspex/blob/8e24d37788b96ba017945c5cea5d2c257d20499a/src/auspex/stream.py#L293) (at least) to break. It seems that `StreamSelector`s should have some protected name.

**Comment by grahamrow** [comment]
Hmm, interesting. We can think of some alternative name in Auspex, though  QGL could perhaps refer to this as "delay" since that's typically what is being changed.

**Comment by dieris** [comment]
yeah, that was exactly my quick fix, if everyone is okay with it (but at least there should be a warning)

**Comment by blakejohnson** [comment]
Renaming the T1/Ramsey/Echo axis to "delay" is fine with me.

**Comment by dieris** [comment]
Fixed by https://github.com/BBN-Q/QGL/pull/100
