### ISSUE TITLE
Slow cartesian product of axes

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#76]
Iterating through the product [here](https://github.com/BBN-Q/Auspex/blob/d3b72f55e22a22bb7eeea70030a7711083b27364/src/auspex/stream.py#L291) can take 10s of  seconds e.g. when the card is in digitizer mode and there are millions of tuples.

**Comment by caryan** [comment]
Indeed... we're running into it too on the probe station measurements.  @grahamrow is aware.

**Comment by grahamrow** [comment]
Should be fixed now, unless you're running pathological unstructured sweeps.
