### ISSUE TITLE
Bokeh slow

### ISSUE THREAD

**Issue by grahamrow** [BBN-Q/Auspex#93]
Image plots (especially with four up) are hilariously slow. Seek mitigation strategy...

**Comment by gribeill** [comment]
Just as a note, I played around with [`jupyter-matplotlib`](https://github.com/matplotlib/jupyter-matplotlib), and while it's nice and draws fast it won't let you interact with a plot in a ipython cell that is being updated... so not sure it's a true replacement for Bokeh.

**Comment by grahamrow** [comment]
Bokeh is being replaced with custom matplotlib client.
